version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
  loki-data:
  promtail-data:
  logs-data:
  prometheus-data:

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - /work/volumes/grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./loki-config.yml:/mnt/config/loki-config.yml
      - /work/volumes/loki-data:/loki
    ports:
      - 3100:3100
    command:
      - '-config.file=/mnt/config/loki-config.yml'
    
  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped 
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /work/volumes/promtail-data:/tmp
      #- /var/log:/var/log
      #- /loghist/:/loghist
      #- /logGyssa/:/logGyssa
      #- /mnt/wasprod01/:/wasprod01/:ro
      #- /mnt/wasprod02/:/wasprod02/:ro
      #- /mnt/wasprod03/:/wasprod03/:ro
    command: -config.file=/etc/promtail/promtail.yml

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /work/volumes/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
        #networks:
        #- monitoring



