global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs: 
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: 
      - localhost:9090

  - job_name: vmwaslocal
    static_configs:
    - targets: ['192.168.110.135:9100']

  - job_name: office
    static_configs:
    - targets: ["10.160.110.6:9182"]

  - job_name: apmproxy
    static_configs:
    - targets: ['10.160.255.171:9100']
  
  - job_name: apmdb
    static_configs:
    - targets: ['10.160.255.170:9100']

  - job_name: vmcmprod01
    static_configs:
    - targets: ['10.160.200.110:9100']





