web:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: 'gitlab.bayronq.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.bayronq.com'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/volumes/gitlab-data/config:/etc/gitlab'
    - '/volumes/gitlab-data/logs:/var/log/gitlab'
    - '/volumes/gitlab-data/data:/var/opt/gitlab'
