services:
    mc:
        command: 'r.microsoft.com/mssql/server:2019-latest'
        image: mc
        container_name: sqlserver
        ports:
            - '1433:1433'
        environment:
            - MSSQL_PID=Express
            - MSSQL_SA_PASSWORD=Admin01.
            - ACCEPT_EULA=Y

