services:
    s-pdf:
        image: 'frooodle/s-pdf:latest'
        container_name: stirling-pdf
        environment:
            - LANGS=es_ES
            - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
            - DOCKER_ENABLE_SECURITY=false
        volumes:
            - './logs:/logs'
            - '/./extraConfigs:/configs'
            - './trainingData:/usr/share/tessdata'
        ports:
            - '8082:8080'

